spring.application.name=aluguel
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/locadora_carro
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework=INFO
logging.level.com.exemplo=INFO

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#RABBITMQ
spring.rabbitmq.host=jackal.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=eqrgexla
spring.rabbitmq.username=eqrgexla
spring.rabbitmq.password=CXoX-m5CjdQ5NlHkVc3KHwqNomuCf1vZ
#FILA
queue.name=qtest
